### ISSUE TITLE
Many wrapping issues

### ISSUE THREAD

**Issue by trentks** [HugoForrat/LaTeX-Vim-User-Manual#2]
Hey mate,

There's many wrapping issues—for instance see page 104 or 120 in release 0.10. Text is too long for the line and doesn't wrap. Pdflatex would have given you many overfull hbox errors for all of these.

Cheers.

**Comment by HugoForrat** [comment]
You're right, I've corrected the tex files for these two mistakes.
I'll search for others instances and I'll update the release and close this issue when I'm done.

I'd be grateful if you could give me the pages where you found other instances, it would speed up the process.
To be quite honest, pdflatex logs are so cryptic that I tend to ignore them, due to laziness or incompetence.

**Comment by HugoForrat** [comment]
So, I've actually found out more mistakes while checking, but as far as I can tell, wrapping issues are no more.
A new release should follow soon.
